### ISSUE TITLE
Is Integrated Security supported ??

### ISSUE THREAD

**Issue by fasilmarshooq** [tareqimbasher/NetPad#252]
I was able to successfully test connection using below connection string 

```
Data Source=<some_server>;Initial Catalog=<some_db>;Integrated Security=True;Trust Server Certificate=True;
```

But fails during scaffolding with error 

```
One or more errors occurred. (No scaffolded files found in output dir.)
```

Note - I am able to make a connection to some other sql server using Basic Auth

**Comment by tareqimbasher** [comment]
It should work yes. Unfortunately the error "No scaffolded files found in output dir" isn't very informative, and hides the true issue. The upcoming update will show the actual error/issue the app faced during scaffolding.

I'll try to test this and see what's going on.

**Comment by fasilmarshooq** [comment]
Thanks for the update.

**Comment by tareqimbasher** [comment]
@fasilmarshooq can you try the [new version](https://github.com/tareqimbasher/NetPad/releases/tag/v0.8.0) and let me know if the issue still persists for you.

**Comment by tareqimbasher** [comment]
This issue should be fixed. Please feel free to reopen if the problem persists with the new version.

**Comment by fasilmarshooq** [comment]
@tareqimbasher   i get this scaffolding issue

```Scaffolding process failed with exit code: 1.
Output: To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
Skipping foreign key 'FK_auth_role_assigned_roles_auth_roles__RoleId' on table 'dbo.auth_role_assigned_roles' since it is a duplicate of 'FK_auth_role_assigned_roles_auth_roles__AssignedRoleId'.
Skipping foreign key 'FK_auth_user_outofoffice_mapping_auth_users_id' on table 'dbo.auth_user_outofoffice_mapping' since it is a duplicate of 'FK_auth_user_outofoffice_mapping_auth_users_assignedid'.
The column 'dbo.configurable_landing_page_happyhour_setting.is_city_accepted' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
The column 'dbo.configurable_landing_page_hotel_setting.is_hotel_enabled' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.
Could not find type mapping for column 'dbo.experiences.coordinate' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo_informations.geo_info' with data type 'geography'. Skipping column.
Unable to scaffold the index 'six01_geography_informations'. The following columns could not be scaffolded: geo_info.
Could not find type mapping for column 'dbo.geo2_area.area_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_area.area_boundary' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_area.map_center_coordinates' with data type 'geography'. Skipping column.
Unable to scaffold the index 'SIndx_geo2_area(area_center_coordinates)'. The following columns could not be scaffolded: area_center_coordinates.
Unable to scaffold the index 'SIndx_geo2_area(map_center_coordinates)'. The following columns could not be scaffolded: map_center_coordinates.
Could not find type mapping for column 'dbo.geo2_city.city_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_city.map_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_city.city_boundary' with data type 'geography'. Skipping column.
Unable to scaffold the index 'IX01_geo2_city(city_center_coordinates)_Spatial'. The following columns could not be scaffolded: city_center_coordinates.
Unable to scaffold the index 'SIndx_geo2_city(map_center_coordinates)'. The following columns could not be scaffolded: map_center_coordinates.
Could not find type mapping for column 'dbo.geo2_continent.continent_boundary' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_continent.map_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_country.country_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_country.country_boundary' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_country.map_center_coordinates' with data type 'geography'. Skipping column.
Unable to scaffold the index 'SIndx_geo2_country(country_center_coordinates)'. The following columns could not be scaffolded: country_center_coordinates.
Unable to scaffold the index 'SIndx_geo2_country(map_center_coordinates)'. The following columns could not be scaffolded: map_center_coordinates.
Could not find type mapping for column 'dbo.geo2_county.county_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_county.county_boundary' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_county.map_center_coordinates' with data type 'geography'. Skipping column.
Unable to scaffold the index 'SIndx_geo2_county(county_boundary)'. The following columns could not be scaffolded: county_boundary.
Unable to scaffold the index 'SIndx_geo2_county(county_center_coordinates)'. The following columns could not be scaffolded: county_center_coordinates.
Unable to scaffold the index 'SIndx_geo2_county(map_center_coordinates)'. The following columns could not be scaffolded: map_center_coordinates.
Could not find type mapping for column 'dbo.geo2_landmark.landmark_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_landmark.landmark_boundary' with data type 'geography'. Skipping column.
Unable to scaffold the index 'SIndx01_geo2_landmark(landmark_center_coordinates)'. The following columns could not be scaffolded: landmark_center_coordinates.
Could not find type mapping for column 'dbo.geo2_local_essential.local_essential_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_region.region_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_region.region_boundary' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_region.map_center_coordinates' with data type 'geography'. Skipping column.
Unable to scaffold the index 'SIndx_geo2_region(map_center_coordinates)'. The following columns could not be scaffolded: map_center_coordinates.
Unable to scaffold the index 'SIndx_geo2_region(region_boundary)'. The following columns could not be scaffolded: region_boundary.
Unable to scaffold the index 'SIndx_geo2_region(region_center_coordinates)'. The following columns could not be scaffolded: region_center_coordinates.
Could not find type mapping for column 'dbo.geo2_state.state_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_state.state_boundary' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_state.map_center_coordinates' with data type 'geography'. Skipping column.
Unable to scaffold the index 'SIndx_geo2_state(map_center_coordinates)'. The following columns could not be scaffolded: map_center_coordinates.
Unable to scaffold the index 'SIndx_geo2_state(state_center_coordinates)'. The following columns could not be scaffolded: state_center_coordinates.
Could not find type mapping for column 'dbo.geo2_tourist_area.tourist_area_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_tourist_area.tourist_area_boundary' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.geo2_tourist_area.map_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.product_hotels.geo_info' with data type 'geography'. Skipping column.
Unable to scaffold the index 'SIndx_product_hotels(geo_info)'. The following columns could not be scaffolded: geo_info.
Could not find type mapping for column 'dbo.sanctioned_territory.sanctioned_territory_boundary_geography' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.sanctioned_territory.sanctioned_territory_boundary_geography_orientation' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.sanctioned_territory.sanctioned_territory_boundary_geometry' with data type 'geometry'. Skipping column.
Unable to scaffold the index 'IX01_SPT_sanctioned_territory__sanctioned_territory_boundary_geography_orientation'. The following columns could not be scaffolded: sanctioned_territory_boundary_geography_orientation.
Could not find type mapping for column 'dbo.tourist_region.tourist_region_center_coordinates' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.tourist_region.tourist_region_boundary' with data type 'geography'. Skipping column.
Could not find type mapping for column 'dbo.tourist_region.map_center_coordinates' with data type 'geography'. Skipping column.
System.InvalidOperationException: The key {'MailId'} cannot be added to keyless type 'EmailMailQueue (Dictionary<string, object>)'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddKey(IReadOnlyList`1 properties)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The key {'MailId'} cannot be added to keyless type 'EmailMailQueue (Dictionary<string, object>)'.
Error: ```

Also I got Ef core error initially `The Entity Framework tools version '8.0.4' is older than that of the runtime '8.0.8'` would be great if its installed as part of app installation.

**Comment by fasilmarshooq** [comment]
unfortunately i cant reopen the issue https://github.com/orgs/community/discussions/41926#discussioncomment-6975082

**Comment by fasilmarshooq** [comment]
FYI, windows auth is working , the issues is when the db has geo related columns

**Comment by tareqimbasher** [comment]
Thanks @fasilmarshooq for confirming windows security works, I'll create a new issue for the spatial data scaffolding problem. I'll test it out and see why EF is having trouble scaffolding it. Thanks for reporting!

**Comment by fasilmarshooq** [comment]
Also, can we have windows auth in the drop-down instead of the user manually fiddling with the connection string ??

**Comment by tareqimbasher** [comment]
Yep, will do.
