### ISSUE TITLE
When the Nuget config contains a Github source, loading the Nuget list is empty

### ISSUE THREAD

**Issue by wf-soft** [tareqimbasher/NetPad#261]
```
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="github" value="https://nuget.pkg.github.com/wf-soft/index.json" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </packageSources>
```

![image](https://github.com/user-attachments/assets/95e0bb81-780d-4633-85e7-b0ddee3d8d6e)

 When I removed the GitHub source, everything was normal

**Comment by tareqimbasher** [comment]
Thanks for reporting. Is that a public feed or a private one? Also can you attach any errors in the Log file. Easiest way to get to it is to open settings, then click open app data folder, where you'll see the logs folder.

**Comment by wf-soft** [comment]
@tareqimbasher 
```
2024-09-18T23:07:21.1463899+08:00 [ERR] (PID: 10736|NetPad.Middlewares.ExceptionHandlerMiddleware) An error occurred in request pipeline
NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve metadata from source 'https://nuget.pkg.github.com/wf-soft/query?q=&skip=0&take=15&prerelease=false&semVerLevel=2.0.0'.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass17_0`1.<<ProcessHttpStreamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Protocol.HttpSource.ProcessResponseAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.HttpSource.ProcessHttpStreamAsync[T](HttpSourceRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageSearchResourceV3.SearchPage[T](Func`2 getResultAsync, String searchTerm, SearchFilter filters, Int32 skip, Int32 take, ILogger log, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.PackageSearchResourceV3.SearchPage[T](Func`2 getResultAsync, String searchTerm, SearchFilter filters, Int32 skip, Int32 take, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.PackageSearchResourceV3.Search[T](Func`3 getResultAsync, String searchTerm, SearchFilter filters, Int32 skip, Int32 take, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.PackageSearchResourceV3.Search(String searchTerm, SearchFilter filters, Int32 skip, Int32 take, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.PackageSearchResourceV3.SearchAsync(String searchTerm, SearchFilter filter, Int32 skip, Int32 take, ILogger log, CancellationToken cancellationToken)
   at NetPad.Packages.NuGet.NuGetPackageProvider.SearchPackagesAsync(String term, Int32 skip, Int32 take, Boolean includePrerelease, Boolean loadMetadata, Nullable`1 cancellationToken) in /home/tips/Source/TIPS/NetPad/src/Core/NetPad.Runtime/Packages/NuGet/NuGetPackageProvider.cs:line 80
   at NetPad.Controllers.PackagesController.Search(String term, Nullable`1 skip, Nullable`1 take, Nullable`1 includePrerelease) in /home/tips/Source/TIPS/NetPad/src/Apps/NetPad.Apps.App/Controllers/PackagesController.cs:line 67
   at lambda_method221(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at NetPad.Middlewares.ExceptionHandlerMiddleware.InvokeAsync(HttpContext httpContext) in /home/tips/Source/TIPS/NetPad/src/Apps/NetPad.Apps.App/Middlewares/ExceptionHandlerMiddleware.cs:line 32
```

**Comment by tareqimbasher** [comment]
Yes, I'll fix that.
