### ISSUE TITLE
SQL Connection Using Active Directory / Microsoft Entra

### ISSUE THREAD

**Issue by kemmis** [tareqimbasher/NetPad#285]
We use Active Directory aka Microsoft Entra to authenticate with all of our SQL servers. I'm not able to find a way to connect using NetPad 0.8.0. Azure Data Studio has the best support/implementation for this. Do you have plans to add this to NetPad? I'd love to use it.

**Comment by tareqimbasher** [comment]
I think it would be a great addition. Its not on README roadmap but it is planned.

**Comment by Tridy** [comment]
not a solution, just a bit more details:

it is possible to add a "Custom" part to the connection string, for example:

`Persist Security Info=False;User ID=xxxxxxx@xxxxx.com;Authentication="Active Directory Interactive";Encrypt=True;`

as a result you get the connection string like this:

`Data Source=xxxxx.database.windows.net,1433;Initial Catalog=xxxxxxxx;Persist Security Info=False;User ID=xxxxxx@xxxxxx.com;Authentication="Active Directory Interactive";Encrypt=True;`

this creates a connection. However the scaffolding shows error:

```
Scaffolding process failed with exit code: 1.
Output: Specify --help for a list of available options and commands.
Unrecognized command or argument 'Interactive;Encrypt=True;'
Error: 
```

**Comment by tareqimbasher** [comment]
@Tridy can you try removing the double quotes from: 

`Authentication="Active Directory Interactive"`

So it's just

`Authentication=Active Directory Interactive`

**Comment by Tridy** [comment]
That indeed helped to start scaffolding

![image](https://github.com/user-attachments/assets/095f88d4-1f0b-49ef-ad39-525a01621630)


However in the process it still got an error:

Could not get database structure during scaffolding. Check the logs at: /home/xxx/.local/share/NetPad/Logs

From the log I can see that it is indeed reading database structure and there is output for several tables in the log.

The error that I can see the most in the log is this:

`Unrecognized command or argument 'Interactive;Encrypt=True;'`

My guess is that it does not like the Interactive part from the "Active Directory Interactive"


and here are some other lines that might have some information

```
System.Text.Json.JsonException: '/' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '/' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   ...
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at NetPad.Common.JsonSerializer.Deserialize[T](String json) in /home/tips/Source/TIPS/NetPad/src/Core/NetPad.Runtime/Common/JsonSerializer.cs:line 36
   at NetPad.Apps.Data.EntityFrameworkCore.Scaffolding.EntityFrameworkDatabaseScaffolder.GetDatabaseStructureAsync(DotNetCSharpProject project, String dbContextClassName) in /home/tips/Source/TIPS/NetPad/src/Apps/NetPad.Apps.Common/Data/EntityFrameworkCore/Scaffolding/EntityFrameworkDatabaseScaffolder.cs:line 130
   
System.Exception: Could not get database structure during scaffolding. Check the logs at: /home/xxx/.local/share/NetPad/Logs
   at NetPad.Apps.Data.EntityFrameworkCore.EntityFrameworkDatabaseConnectionMetadataProvider.GetDatabaseStructureAsync(DatabaseConnection databaseConnection) in /home/tips/Source/TIPS/NetPad/src/Apps/NetPad.Apps.Common/Data/EntityFrameworkCore/EntityFrameworkDatabaseConnectionMetadataProvider.cs:line 41
   at NetPad.Apps.CQs.GetDatabaseConnectionStructureQuery.Handler.Handle(GetDatabaseConnectionStructureQuery request, CancellationToken cancellationToken) in /home/tips/Source/TIPS/NetPad/src/Apps/NetPad.Apps.Common/CQs/GetDatabaseConnectionStructureQuery.cs:line 17
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at NetPad.Services.MediatorRequestPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /home/tips/Source/TIPS/NetPad/src/Apps/NetPad.Apps.App/Services/MediatorRequestPipeline.cs:line 18
   at NetPad.Plugins.OmniSharp.OmniSharpMediatorPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /home/tips/Source/TIPS/NetPad/src/Plugins/NetPad.Plugins.OmniSharp/OmniSharpMediatorPipeline.cs:line 15
   at NetPad.Controllers.DataConnectionsController.GetDatabaseStructure(Guid id) in /home/tips/Source/TIPS/NetPad/src/Apps/NetPad.Apps.App/Controllers/DataConnectionsController.cs:line 103
   at lambda_method154(Closure , Object )
   ...
   at NetPad.Middlewares.ExceptionHandlerMiddleware.InvokeAsync(HttpContext httpContext) in /home/tips/Source/TIPS/NetPad/src/Apps/NetPad.Apps.App/Middlewares/ExceptionHandlerMiddleware.cs:line 32

2024-11-14T22:18:09.6337918+01:00 [ERR] (PID: 137620|NetPad.Apps.Data.EntityFrameworkCore.Scaffolding.EntityFrameworkDatabaseScaffolder) Ran database structure generation successfully but failed to deserialize output. JSON: /tmp/NetPad/TypedDataContexts/40f43120-5c33-4f3c-8178-b37039442cb2/DataConnection_40f43120-5c33-4f3c-8178-b37039442cb2.csproj
```
