### ISSUE TITLE
Any chance of getting pre-built binaries?

### ISSUE THREAD

**Issue by ChristopherHaws** [tareqimbasher/NetPad#30]
Could we get some pre-built binaries? Even if they are artifacts of the github action that would be ok. I can't seem to get the project to build locally.

```shell
electronize build /target win /manifest electron.manifest.js /PublishSingleFile false
Build Electron Application...
Arguments:
        target = win
        manifest = electron.manifest.js
        PublishSingleFile = false
Build ASP.NET Core App for win-x64...
Executing dotnet publish in this directory: C:\dev\github\NetPad\src\Apps\NetPad.Apps.App\obj\desktop\win
Build ASP.NET Core App for win-x64 under Release-Configuration...
dotnet publish -r win-x64 -c "Release" --output "C:\dev\github\NetPad\src\Apps\NetPad.Apps.App\obj\desktop\win\bin" /p:PublishReadyToRun=true /p:PublishSingleFile=false --self-contained
dotnet publish -r win-x64 -c "Release" --output "C:\dev\github\NetPad\src\Apps\NetPad.Apps.App\obj\desktop\win\bin" /p:PublishReadyToRun=true /p:PublishSingleFile=false --self-contained
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  O2Html -> C:\dev\github\NetPad\src\External\O2Html\bin\Release\net6.0\O2Html.dll
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\Settings.cs(10,12): warning CS8618: Non-nullable property 'Version' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\Settings.cs(10,12): warning CS8618: Non-nullable property 'ScriptsDirectoryPath' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\Settings.cs(10,12): warning CS8618: Non-nullable property 'AutoSaveScriptsDirectoryPath' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\Settings.cs(10,12): warning CS8618: Non-nullable property 'PackageCacheDirectoryPath' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\Settings.cs(10,12): warning CS8618: Non-nullable property 'Appearance' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\Settings.cs(10,12): warning CS8618: Non-nullable property 'Editor' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\Settings.cs(10,12): warning CS8618: Non-nullable property 'Results' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\Settings.cs(10,12): warning CS8618: Non-nullable property 'OmniSharp' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\EditorOptions.cs(7,12): warning CS8618: Non-nullable property 'MonacoOptions' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\OmniSharpOptions.cs(11,12): warning CS8618: Non-nullable property 'Diagnostics' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\Configuration\OmniSharpOptions.cs(11,12): warning CS8618: Non-nullable property 'InlayHints' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
C:\dev\github\NetPad\src\Core\NetPad.Domain\IO\ProcessHandler.cs(94,30): warning CS0168: The variable 'ex' is declared but never used [C:\dev\github\NetPad\src\Core\NetPad.Domain\NetPad.Domain.csproj]
  NetPad.Domain -> C:\dev\github\NetPad\src\Core\NetPad.Domain\bin\Release\net6.0\NetPad.Domain.dll
  NetPad.Compilation -> C:\dev\github\NetPad\src\Core\NetPad.Compilation\bin\Release\net6.0\NetPad.Compilation.dll
  NetPad.InMemoryScriptRuntime -> C:\dev\github\NetPad\src\Infrastructure\ScriptRuntimes\NetPad.InMemoryScriptRuntime\bin\Release\net6.0\NetPad.InMemoryScriptRuntime.dll
  NetPad.Application -> C:\dev\github\NetPad\src\Core\NetPad.Application\bin\Release\net6.0\NetPad.Application.dll
  NetPad.Presentation -> C:\dev\github\NetPad\src\Core\NetPad.Presentation\bin\Release\net6.0\NetPad.Presentation.dll
  NetPad.Infrastructure -> C:\dev\github\NetPad\src\Infrastructure\NetPad.Infrastructure\bin\Release\net6.0\NetPad.Infrastructure.dll
  OmniSharp.NET -> C:\dev\github\NetPad\src\External\OmniSharp.NET\bin\Release\netstandard2.1\OmniSharp.NET.dll
  NetPad.Web -> C:\dev\github\NetPad\src\Infrastructure\NetPad.Web\bin\Release\net6.0\NetPad.Web.dll
C:\dev\github\NetPad\src\Infrastructure\ScriptRuntimes\NetPad.ExternalProcessScriptRuntime\ScriptRuntimeServices.cs(7,31): warning CS8618: Non-nullable field '_defaultConsoleOutput' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [C:\dev\github\NetPad\src\Infrastructure\ScriptRuntimes\NetPad.ExternalProcessScriptRuntime\NetPad.ExternalProcessScriptRuntime.csproj]
  NetPad.ExternalProcessScriptRuntime -> C:\dev\github\NetPad\src\Infrastructure\ScriptRuntimes\NetPad.ExternalProcessScriptRuntime\bin\Release\net6.0\NetPad.ExternalProcessScriptRuntime.dll
  NetPad.Electron -> C:\dev\github\NetPad\src\Infrastructure\NetPad.Electron\bin\Release\net6.0\NetPad.Electron.dll
  NetPad.Plugins.OmniSharp -> C:\dev\github\NetPad\src\Plugins\NetPad.Plugins.OmniSharp\bin\Release\net6.0\NetPad.Plugins.OmniSharp.dll
  NetPad.Apps.App -> C:\dev\github\NetPad\src\Apps\NetPad.Apps.App\bin\Release\net6.0\win-x64\NetPad.Apps.App.dll

  up to date, audited 1069 packages in 2s

  121 packages are looking for funding
    run `npm fund` for details

  6 high severity vulnerabilities

  To address all issues (including breaking changes), run:
    npm audit fix --force

  Run `npm audit` for details.

  > build
  > rimraf dist && webpack --env production

  Run info:
     Environment: production
     Target: electron
  assets by path *.js 6.57 MiB
    assets by chunk 195 KiB (id hint: vendors)
      asset 665.270ca4fd3552015cefc4.bundle.js 39.6 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
      asset 5377.827b384e58cbef5a1308.bundle.js 34.1 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
      asset 5288.e1df5ceb341be95433e9.bundle.js 33.5 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
      asset 8401.c512ca671f3001b316c2.bundle.js 22.3 KiB [emitted] [immutable] [minimized] (id hint: vendors)
      asset 1156.4486bf557a5dc271495d.bundle.js 18.2 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
      + 3 assets
    + 76 assets
  assets by chunk 603 KiB (auxiliary name: entry)
    asset 422cfe2813b03d900c10.ttf 381 KiB [emitted] [immutable] [from: node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.ttf] (auxiliary name: entry)
    asset 64d495f582d4a1590a6c.woff2 151 KiB [emitted] [immutable] [from: node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2] (auxiliary name: entry)
    asset b797181c93b3755f4fa1.ttf 70.8 KiB [emitted] [immutable] [from: node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf] (auxiliary name: entry)
  asset favicon.ico 118 KiB [emitted]
  asset index.html 330 bytes [emitted]
  orphan modules 4.34 MiB [orphan] 634 modules
  runtime modules 11.5 KiB 13 modules
  built modules 11.7 MiB (javascript) 603 KiB (asset) [built] 618 modules
  webpack 5.74.0 compiled successfully in 52844 ms
  NetPad.Apps.App -> C:\dev\github\NetPad\src\Apps\NetPad.Apps.App\obj\desktop\win\bin\


Start npm install...
npm install --production
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 69 packages, and audited 70 packages in 2s

found 0 vulnerabilities


ElectronHostHook handling started...
Build Electron Desktop Application...
Executing electron magic in this directory: C:\dev\github\NetPad\src\Apps\NetPad.Apps.App\bin\desktop
Create electron-builder configuration file...
node build-helper.js electron.manifest.js


Package Electron App for Platform win...
npx electron-builder --config=./bin/electron-builder.json --win --x64 -c.electronVersion=13.1.5
  • electron-builder  version=23.6.0 os=10.0.22621
  • loaded configuration  file=C:\dev\github\NetPad\src\Apps\NetPad.Apps.App\obj\desktop\win\bin\electron-builder.json
  ⨯ Invalid configuration object. electron-builder 23.6.0 has been initialized using a configuration object that does not match the API schema.
 - configuration.linux.target[2] has an unknown property 'depends'. These properties are valid:
   object { target, arch? }
     How to fix:
     1. Open https://www.electron.build/configuration/linux
     2. Search the option name on the page (or type in into Search to find across the docs).
       * Not found? The option was deprecated or not exists (check spelling).
       * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.
  failedTask=build stackTrace=ValidationError: Invalid configuration object. electron-builder 23.6.0 has been initialized using a configuration object that does not match the API schema.
 - configuration.linux.target[2] has an unknown property 'depends'. These properties are valid:
   object { target, arch? }
     How to fix:
     1. Open https://www.electron.build/configuration/linux
     2. Search the option name on the page (or type in into Search to find across the docs).
       * Not found? The option was deprecated or not exists (check spelling).
       * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.



                                                                      at validate (C:\Users\cribs\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\@develar\schema-utils\dist\validate.js:86:11)
    at Object.validateConfig (C:\Users\cribs\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-lib\src\util\config.ts:240:3)
    at Packager._build (C:\Users\cribs\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-lib\src\packager.ts:342:5)
    at Packager.build (C:\Users\cribs\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (C:\Users\cribs\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\builder-util\src\promise.ts:12:14)


... done
```

**Comment by tareqimbasher** [comment]
@ChristopherHaws the plan is to publish the binaries in the first "alpha" release over the next few days. I was planning on pushing out a release last week, but I delayed it due to an internally reported bug with some database connections on Windows.

As far as the build error you're getting, pull the last commit from `main`, somehow I missed pushing that last commit a few days ago. You should be able to build the app just fine after that.

**Comment by tareqimbasher** [comment]
@ChristopherHaws the [first alpha release](https://github.com/tareqimbasher/NetPad/releases/tag/v0.1.0) is out with binaries ready to use 😃
