### ISSUE TITLE
SqlClient PlatformNotSupported_DataSqlClient

### ISSUE THREAD

**Issue by jkdufair** [tareqimbasher/NetPad#69]
Very excited about this app! Went ahead and installed it on my x86 mac running macOS 13.4.1 with dotnet version 6.0.301 and efcore tools 7.0.9. I'm able to connect to my local Sql Server running in a docker container and can view the db schema in the left hand pane. When I try to run a LINQ query against that database I get the following error. Have I not configured things correctly somehow?

```
System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.<>c.<get_IsMultipleActiveResultSetsEnabled>b__7_0(String cs)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.get_IsMultipleActiveResultSetsEnabled()
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.IEnumerable.GetEnumerator()
   at O2Html.Common.LazyEnumerable.Enumerate[T](IEnumerable collection, Nullable`1 maxItemsToEnumerate, Action`2 action)
   at O2Html.Converters.CollectionHtmlConverter.Convert[T](T obj, Type type, SerializationScope serializationScope, HtmlSerializer htmlSerializer)
   at O2Html.Converters.CollectionHtmlConverter.WriteHtml[T](T obj, Type type, SerializationScope serializationScope, HtmlSerializer htmlSerializer)
   at O2Html.HtmlSerializer.Serialize[T](T obj, Type type, SerializationScope serializationScope)
   at O2Html.HtmlConvert.Serialize[T](T obj, HtmlSerializerSettings htmlSerializerSettings)
   at NetPad.Html.HtmlSerializer.Serialize(Object output, String title, Boolean isError)
```

**Comment by tareqimbasher** [comment]
Thank you for reporting this issue. I don't think that's anything you're doing incorrectly, I'll look into this. Out of curiosity do you see the same issue if you use v0.4.0?

Glad you're enjoying the app!

**Comment by tareqimbasher** [comment]
I found the issue, there are MS SQL specific assemblies missing from the Mac build. I will release a hotfix release soon.

**Comment by tareqimbasher** [comment]
Until the hotfix is released, to immediately fix this issue, extract this and copy the `Assets` folder to `/path/to/NetPad.app/Contents/Resources/bin`

[MissingAssemblies.zip](https://github.com/tareqimbasher/NetPad/files/12270849/MissingAssemblies.zip)

**Comment by jkdufair** [comment]
Thanks for digging into this!
